remote_theme: pages-themes/merlot@v0.2.0
plugins:
  - jekyll-remote-theme
relative_links:
  enabled: true
  collections: true
title: SimTalk Styleguide
description: An opinionated styleguide for the scripting language SimTalk used in Tecnomatix Plant Simulation.
